### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by stSaHiB** [firephp/firephp-for-firebug.next#10]
Hi Christophe,

i dont get it working with Firefox Developer Edition 53.

I'm using FirePHP for many years, integrated some miner Bugfuxes by myself, after the old extensions seemed to be no longer maintained.  But with latest FF51 update I dont get it working any more  (it's posting debug data to the console of the next/prev tab, instead of current), so I looked around, finding this extension.

**Is there any chance you get this extension working with current devtools within the next time? 
And will you keep maintaining it?**

I will hate switching to some other PHP-Lib like Chrome Logger - it really su** - but with you having no time to take care about firePHP, I will be forced to :-(
And if you don't continue - please end the project, telling everybody that it's dead, instead of letting it sneak around the web like a zombi...

in either way: thanks a lot for your efforts - FirePHP made developers life so much easier!
sahib

**Comment by cadorn** [comment]
A new FirePHP extension has been released that works for Firefox >= 56.0.2.

See: http://firephp.org/
