### ISSUE TITLE
I could not find/ not working firephp in firefox 

### ISSUE THREAD

**Issue by Misikir** [firephp/firephp-for-firebug.next#8]
## Application Basics

Name: Firefox
Version: 41.0b4
Build ID: 20150824144923
Update Channel: beta
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0
Multiprocess Windows: 0/1 (default: false)

Name: Firebug
Version: 3.0.0-alpha.13
Enabled: true
ID: firebug@software.joehewitt.com

Name: FirePHP for Firebug.Next
Version: 0.1.0
Enabled: true
ID: firephp-for-firebug.next@firephp.org

**Comment by cadorn** [comment]
You need to use Firebug 2.x for now.

**Comment by cadorn** [comment]
A new FirePHP extension has been released that works for Firefox >= 56.0.2.

See: http://firephp.org/
