### ISSUE TITLE
How to get Pre-Release working in Nightly

### ISSUE THREAD

**Issue by aolin480** [firephp/firephp-for-firebug.next#9]
I've been following the progress with FirePHP for Firebug Next, and I saw in the notes that it requires Firefox Nightly. I do not see a FirePHP panel in Firebug 3.0. 

I have it installed firebug-3.0.0-beta.3.xpi from https://getfirebug.com/releases/firebug/3.0/, unless there's another Firebug I need to install? I am happy to do whatever it is to make it work, even if I need to install some external libraries, etc. I am on a Mac.

Hope all is well!

Thanks!

**Comment by cadorn** [comment]
Its not quite functional yet. I hope to get some time to finish it soon.

**Comment by cadorn** [comment]
A new FirePHP extension has been released that works for Firefox >= 56.0.2.

See: http://firephp.org/
